apiVersion: skaffold/v3
kind: Config
build:
 local:
  push: false
 artifacts:
  - image: af912/post-friends-club
    context: .
    sync:
     manual:
     - src: src/**/*.ts
       dest: .
    docker:
      dockerfile: ./apps/post/Dockerfile
  - image: af912/interaction-friends-club
    context: .
    sync:
     manual:
     - src: src/**/*.ts
       dest: .
    docker:
      dockerfile: ./apps/interaction/Dockerfile
  - image: af912/client-friends-club
    context: ../friends-club-frontend/
    sync:
     manual:
     - src: src/**/*.ts
       dest: .
     - src: src/**/*.tsx
       dest: .
    docker:
      dockerfile: Dockerfile
  - image: af912/user-friends-club
    context: .
    sync:
     manual:
     - src: src/**/*.ts
       dest: .
    docker:
      dockerfile: ./apps/user/Dockerfile
manifests:
 rawYaml:
 - ./infra/k8s/*
 - ./infra/dev/*
deploy:
 kubectl: {}