apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-depl
spec:
  selector:
    matchLabels:
      app: post
  # replicas: 2
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
      - name: post
        image: af912/post-friends-club
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: post-srv
spec:
  selector:
    app: post
  ports:
  - name: post
    protocol: TCP
    port: 8000
    targetPort: 8000
  

