apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-depl
spec:
  selector:
    matchLabels:
      app: user
  replicas: 1
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: af912/user-friends-club:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        envFrom:
        - secretRef:
            name: user
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: user-srv
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8000
  selector:
    app: user

