apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: friends-club-ingress
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "6m"
    nginx.ingress.kubernetes.io/upstream-healthcheck-path: "/api/post/health"
    nginx.ingress.kubernetes.io/upstream-healthcheck-interval: "10"
    nginx.ingress.kubernetes.io/upstream-healthcheck-timeout: "5"
    nginx.ingress.kubernetes.io/upstream-healthcheck-fails: "3"
    nginx.ingress.kubernetes.io/upstream-healthcheck-passes: "1"
    # nginx.ingress.kubernetes.io/use-regex: "true"
  labels:
    name: friends-club-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: friends-club.dev
    http:
      paths:
      - pathType: ImplementationSpecific
        path: /api/post/?(.*)
        backend:
          service:
            name: post-srv
            port: 
              number: 8000
      - pathType: ImplementationSpecific
        path: /api/reaction/?(.*)
        backend:
          service:
            name: interaction-srv
            port: 
              number: 8000
      - pathType: ImplementationSpecific
        path: /api/user/?(.*)
        backend:
          service:
            name: user-srv
            port: 
              number: 8000
      - pathType: ImplementationSpecific
        path: /?(.*)
        backend:
          service:
            name: client-srv
            port: 
              number: 3000