name: deploy

on:
  push:
    branches:
      - main
    paths:
      - "apps/interaction/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Print current directory
        run: pwd && ls -la

      - name: Build Docker image
        run: docker build -f apps/interaction/Dockerfile ../../ -t af912/interaction-friends-club

      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push the docker image
        run: docker push af912/interaction-friends-club
