name: Test

on: 
  pull_request:
    paths:
      - "apps/interaction/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install -g pnpm
      - run: pnpm install --frozen-lockfile && nest build interaction && pnpm run test --testPathPattern=interaction