name: Test user

on: 
  pull_request:
    paths:
      - "apps/user/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependecies
        run: pnpm install
    
      - name: Lint code
        run: npx eslint apps/user/**/*.ts --fix

      - name: Create build
        run: npx nest build user 
      