name: Test

on: 
  pull_request:
    paths:
      - "apps/interaction/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependecies
        run: pnpm install
    
      - name: Lint code
        run: pnpm run lint -- --fix
        working-directory: apps/interaction

      - name: Create build
        run: npx nest build interaction 

      - name: Run tests
        run: pnpm run test --testPathPattern=interaction
      