name: Test

on: 
  pull_request:
    paths:
      - "apps/post/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependecies
        run: pnpm install
    
      - name: Lint code
        run: npx eslint apps/post/**/*.ts --fix

      - name: Create build
        run: npx nest build post 

      - name: Run tests
        run: pnpm run test --testPathPattern=post
      